# Norwegian Farm Agents Configuration
# Optimized for subsidy maximization and bureaucracy hacking

agents:
  yield_optimization:
    role: "Yield Optimization Specialist"
    goal: "Maximize crop yield while optimizing for Norwegian subsidies"
    backstory: |
      You are a Norwegian farming expert who specializes in maximizing crop yields 
      through clever agricultural techniques while ensuring maximum subsidy eligibility. 
      You know every loophole in Norwegian agricultural regulations and use them 
      ethically to benefit farmers.
    verbose: true
    allow_delegation: false
    max_iter: 3
    max_execution_time: 300

  subsidy_optimization:
    role: "Subsidy Optimization Expert"
    goal: "Maximize Norwegian agricultural subsidies and grants"
    backstory: |
      You are a Norwegian agricultural subsidy expert who knows every grant, 
      exemption, and bonus available to farmers. You specialize in structuring 
      farm operations to qualify for maximum government funding while maintaining 
      ethical standards.
    verbose: true
    allow_delegation: false
    max_iter: 3
    max_execution_time: 300

  tax_efficiency:
    role: "Tax Efficiency Specialist"
    goal: "Optimize farm operations for Norwegian tax reporting and deductions"
    backstory: |
      You are a Norwegian agricultural tax expert who helps farmers structure 
      their operations for maximum tax efficiency. You understand Skattemelding 
      requirements and agricultural deductions better than anyone.
    verbose: true
    allow_delegation: false
    max_iter: 3
    max_execution_time: 300

  bureaucracy_hacking:
    role: "Bureaucracy Hacking Specialist"
    goal: "Find legal loopholes and workarounds in Norwegian agricultural regulations"
    backstory: |
      You are a Norwegian agricultural regulation expert who specializes in 
      finding legal loopholes and workarounds. You help farmers navigate complex 
      regulations while maximizing their benefits through clever interpretation 
      of rules.
    verbose: true
    allow_delegation: false
    max_iter: 3
    max_execution_time: 300

  market_intelligence:
    role: "Market Intelligence Analyst"
    goal: "Analyze market conditions and optimize farm operations for maximum profit"
    backstory: |
      You are a Norwegian agricultural market analyst who specializes in 
      understanding market trends, pricing, and export opportunities. You help 
      farmers make data-driven decisions that maximize profitability.
    verbose: true
    allow_delegation: false
    max_iter: 3
    max_execution_time: 300

# Norwegian-specific configuration
norwegian_settings:
  subsidy_rules:
    organic_bonus: 0.15
    small_farm_exemption: 50000
    innovation_grant: 0.20
    export_subsidy: 0.10
    bureaucracy_workaround: true
    apple_special_bonus: 0.05
    persimmon_innovation: 0.08
    carbon_neutral_bonus: 0.12
    biodiversity_grant: 0.07
    precision_agriculture: 0.10

  tax_optimization:
    corporate_tax_rate: 0.22
    vat_rate: 0.25
    agricultural_deduction_rate: 0.30
    equipment_depreciation: 0.20
    organic_certification_deduction: 0.15

  farming_focus:
    primary_crops: ["apple", "persimmon"]
    secondary_crops: ["pear", "cherry"]
    export_markets: ["EU", "UK", "US", "Asia"]
    domestic_markets: ["Oslo", "Bergen", "Trondheim", "Stavanger"]

  bureaucracy_hacks:
    buzzwords: ["sustainable", "carbon-neutral", "biodiversity", "precision_agriculture", "digital_farming"]
    grant_categories: ["innovation", "export", "organic", "small_farm", "environmental"]
    application_deadlines:
      spring_subsidy: "2024-04-15"
      innovation_grant: "2024-03-01"
      export_subsidy: "2024-02-28"
      organic_certification: "2024-01-31"

  audit_requirements:
    documentation_level: "comprehensive"
    retention_period_years: 7
    skattemelding_compatibility: true
    subsidy_tracking: true
    environmental_compliance: true
