global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'nordic-farm-backend'
    static_configs:
      - targets: ['backend:3001']
    metrics_path: '/api/metrics'
    scrape_interval: 5s

  - job_name: 'nordic-farm-content-agent'
    static_configs:
      - targets: ['content-agent:8030']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'nordic-farm-integration'
    static_configs:
      - targets: ['integration:8031']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'nordic-farm-frontend'
    static_configs:
      - targets: ['frontend:8081']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
