name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
      - name: Setup pnpm
        run: npm i -g pnpm@9
      - name: Install deps (prefer pnpm)
        run: |
          if [ -f pnpm-lock.yaml ]; then pnpm i --frozen-lockfile; else npm ci; fi
      - name: Typecheck
        run: |
          if npm run | grep -q typecheck; then npm run typecheck || pnpm typecheck; else echo 'no typecheck script'; fi
      - name: Lint
        run: |
          if npm run | grep -q lint; then npm run lint || pnpm lint; else echo 'no lint script'; fi
      - name: Build
        run: |
          if npm run | grep -q build; then npm run build || pnpm build; else echo 'no build script'; fi

  python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: farm_ai_crew
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy pytest pytest-cov
      - name: Lint (ruff)
        run: ruff check .
      - name: Typecheck (mypy)
        run: mypy src
      - name: Tests
        run: |
          if [ -d tests ] || ls -1 *.py 2>/dev/null | grep -q test_; then pytest -q --maxfail=1 --disable-warnings; else echo 'no tests'; fi
